version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
    # links:
    #   - mongo
    # depends_on:
    #   - mongo
    environment:
        MONGO_URL: mongodb://mongo:27017/mongodb
        BOT_TOKEN: 1524380805:AAEVbtnt82_B2-w1_bmERK2G-4l86Z3hc10
        GROUP_INVITE_LINK: https://t.me/+VEoHHOeZWxTDGc9A
    # networks:
    #   - node-webapp-network

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
        # MONGO_INITDB_ROOT_USERNAME: mongoadmin
        # MONGO_INITDB_ROOT_PASSWORD: <admin-password>
        MONGO_INITDB_DATABASE: mongodb   
    volumes:
      - mongodb:/data/db
    # networks:
    #   - node-webapp-network      
volumes:
 mongodb:

# networks:
#   node-webapp-network:
#     driver: bridge  


